=== iliakovalevich/laba_3_4_xml_dtd/file.dtd
<!ELEMENT subjects (subject+)>
<!ELEMENT subject (subject_id,title,teacher,additionally+)>

<!ELEMENT subject_id (#PCDATA)>
<!ATTLIST subject_id data_byte CDATA #FIXED "INTEGER">

<!ELEMENT title (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>

<!ELEMENT additionally (original,lesson_hours+,pass_cost)>

<!ELEMENT original (#PCDATA)>
<!ATTLIST original language CDATA #REQUIRED>
<!ELEMENT pass_cost (#PCDATA)>

<!ELEMENT lesson_hours (lab_hours,lection_hours)>

<!ELEMENT lab_hours (#PCDATA)>
<!ELEMENT lection_hours (#PCDATA)>

=== iliakovalevich/laba_3_4_xml_dtd/file.xml
<?xml version="1.0" encoding = "utf-8"?>
<!DOCTYPE subjects SYSTEM "file.dtd">

<subjects>
    <subject>
        <subject_id> 001 </subject_id>
        <title> Object oriented programming </title>
        <teacher> Skrashuk Vladislav </teacher>
        <teacher>Olizarovich</teacher>
        <additionally>
            <subject_langiage language = "Russian" />
            <lesson_hours>
                <lab_hours>20</lab_hours>
                <lection_hours>30</lection_hours>
            </lesson_hours>
            <pass_cost>4.5</pass_cost>
        </additionally>
    </subject>

    <subject>
        <subject_id> 002 </subject_id>
        <title> Foreign language </title>
        <teacher> Bukova Oksana </teacher>
        <additionally>
            <subject_langiage language = "English" />
            <lesson_hours>
                <lab_hours>30</lab_hours>
                <lection_hours>40</lection_hours>
            </lesson_hours>
            <pass_cost>4.5</pass_cost>
        </additionally>
    </subject>

    <subject>
        <subject_id> 003 </subject_id>
        <title> Computer systems and networks </title>
        <teacher> Olizarovich Evgenii </teacher>
        <additionally>
            <subject_langiage language = "Russian" />
            <lesson_hours>
                <lab_hours>20</lab_hours>
                <lection_hours>26</lection_hours>
            </lesson_hours>
            <pass_cost>4.5</pass_cost>
        </additionally>
    </subject>

</subjects>
